-- AlterTable
ALTER TABLE "Articulo" ALTER COLUMN "imagen" DROP NOT NULL,
ALTER COLUMN "descripcion" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Donacion" ALTER COLUMN "monto" DROP NOT NULL,
ALTER COLUMN "mensaje" DROP NOT NULL;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "email" DROP NOT NULL,
ALTER COLUMN "password" DROP NOT NULL,
ALTER COLUMN "role" SET DEFAULT 'ADMIN';
